### PR TITLE
Update click dependency

### PR DESCRIPTION
**Pull request by ViridianForge**
- Update click dependency to be compatible with black's requirements for click
- Update generated protobufs to be compatible with protobuf >3.20.0

### CODE REVIEW

**Comment by ViridianForge** [comment]
Sorry to bug you on an archived repo @wesky93 - but I've been running into an dependency incompatibility using grpc_requests in a monorepo project due to the black project pinning their click dependency to >=8.0.0.

This PR updates that dependency, and updates the generated protobufs so I could confirm tests were still passing.

**Comment by wesky93** [comment]
@ViridianForge 
To run the deployment pipeline
Please change the develop branch to the target branch.

**Comment by wesky93** [comment]
When I prepare the next version of grpc_requests,
Let's remove the dependency on homi from grpc_requests.

**Comment by wesky93** [comment]
oh.. I can change target branch! :)

**Review by wesky93 — APPROVED** [review]

**Comment by ViridianForge** [comment]
Thanks for getting that! Apologies for targeting the incorrect branch.
I'll see if I can get some time this weekend to remove the dependency from grpc_requests!

**Pull request merged**
